name: test workflow
on:
  workflow_dispatch:
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: ./.github/actions/test
      - name: other
        run:
          echo 'test'
      - name: remove github folder
        run:
          rm -Rf .github